config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :fans, :controllers => { registrations: 'registrations' }
  resources :dishes, only: [:index, :show, :new, :create, :edit, :update] do 
    collection do
      get '/dishes/mydishes',
       to: 'dishes#mydishes'
    end
    member do
      put 'like', to: 'dishes#upvote'
      put 'dislike', to: 'dishes#downvote'
      get '/dishes/published', to: 'dishes#published'
      get '/dishes/unpublished', to: 'dishes#unpublished'
    end
  end
  root to: "dishes#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/dish.rb
class Dish < ActiveRecord::Base
	 acts_as_votable
   belongs_to :fan

   validates :title, :description, presence: true
   validates :cost, :pax, numericality: { greater_than: 0 }

   scope :search_keyword, ->(keyword) { where('title ILIKE ?', "#{keyword}%") }
   scope :getDishesByFan, ->(fan_id)  { where('fan_id = ?', fan_id) }
   scope :published,      ->          { where(published: true) }
   scope :approved,       ->          { where(approved: true) }
end

app/models/fan.rb
class Fan < ActiveRecord::Base
	 acts_as_voter
   has_many :dishes
   
   validates :first_name, :last_name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController

   before_filter :authenticate_fan!, only: [:new, :create, :edit, :update]

   def index
      if keyword.blank?
         @dishes = Dish.published.approved
      else
         @dishes = Dish.search_keyword(keyword).published.approved
      end
   end

   def show
      @dish = Dish.find(dish_id)
   end

   def new
      @dish = Dish.new
   end

   def create
      @dish = Dish.new(dish_params)
      if @dish.save
         redirect_to dishes_url, notice: "you have successfully created a dish!"             
      else
         flash.now[:error] = "There is an error to create your dish"
         render :new
      end
   end

    def edit
      @dish = Dish.find(dish_id)
      render :new
   end

   def update
      @dish = Dish.find(dish_id)
      if @dish.update(dish_params)
         redirect_to dishes_url, notice: "you have successfully updated a dish!" 
      else
         flash.now[:error] = "There is an error to update your dish"
         render :new
      end
   end

   def mydishes
      @dishes = Dish.getDishesByFan(current_fan.id) if current_fan.present?
   end

   def published
      @dish = Dish.find(dish_id)
      @dish.published = true

      if @dish.save
         flash[:notice] = "You have published dish successfully"
      else
         flash.now[:error] = "There is an error to published your dish"
      end
      redirect_to dishes_mydishes_dishes_url
   end

   def unpublished
      @dish = Dish.find(dish_id)
      @dish.published = false

      if @dish.save
         flash[:notice] = "You have unpublished dish successfully"
      else
         flash.now[:error] = "There is an error to unpublished your dish"
      end
      redirect_to dishes_mydishes_dishes_url
   end

   def upvote
      @dish = Dish.find(dish_id)
      @dish.upvote_by current_fan
      redirect_to :back
   end

   def downvote
      @dish = Dish.find(dish_id)
      @dish.downvote_by current_fan
      redirect_to :back
   end


   private

   def dish_id
      params.require(:id)
   end

   def keyword
      params[:keyword]
   end

   def dish_params
      params.require(:dish).permit(:title, :description, :cost, :pax, :vegetarian, :fan_id, :published).merge(fan_id: current_fan.id)
   end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

   private

   def sign_up_params
    params.require(:fan).permit(:first_name, :last_name, :email, :password, :password_confirmation)
   end

   def account_update_params
    params.require(:fan).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dishes/index.html.slim
h1 Listing the dishes

#dishes_search
  = form_tag dishes_path, method: 'get'
    = text_field_tag :keyword, params[:keyword]
    = submit_tag "Search", :name => nil
br    
#dishes_index
 - if @dishes.any?              
    table.table.table-striped.table-bordered
      thead
        tr
          th Title
          th Description
          th Cost
          th Pax
          th Vegetarian
          th Action
      tbody
        - @dishes.each do |dish|
          tr
           td = link_to dish.title, dish_path(dish)
           td = dish.description
           td = number_to_currency(dish.cost, precision: 2)
           td = dish.pax
           td = dish.vegetarian
           td 
            - if current_fan.present?
              = link_to 'Edit', edit_dish_path(dish) if current_fan.id == dish.fan_id
 - else
    p.message.clear
      | "No dishes found! Thank you"

p = link_to 'Create a Dish', new_dish_path
         

app/views/dishes/mydishes.html.slim
h1 Listing my dishes
   
#dishes_index
 - if @dishes.any?              
    table.table.table-striped.table-bordered
      thead
        tr
          th Title
          th Description
          th Cost
          th Pax
          th Vegetarian
          th Action
      tbody
        - @dishes.each do |dish|
          tr
           td = link_to dish.title, dish_path(dish)
           td = dish.description
           td $ #{dish.cost}
           td = dish.pax
           td = dish.vegetarian
           td 
            - if current_fan.present?
              = link_to 'Edit ', edit_dish_path(dish) if current_fan.id == dish.fan_id
              - if dish.published
                = link_to 'Unpublished', dishes_unpublished_dish_path(dish)
              - else
                = link_to 'Published', dishes_published_dish_path(dish) 
 - else
    p.message.clear
      | "No dishes found! Thank you"

         

app/views/dishes/new.html.slim
h1 Create a Dish
#dishes_form
   = semantic_form_for @dish do |f|
      .form-group 
         .title = f.input  :title
      .form-group    
         .description = f.input  :description
      .form-group 
         .cost = f.input  :cost, min: 0.01
      .form-group 
         .pax = f.input  :pax
      .form-group 
         .vegetarian = f.input  :vegetarian
      .form-group 
         .published = f.input  :published
      .form-group 
         = f.action :submit

app/views/dishes/show.html.slim
.container
   #dishes-show
      h1 = @dish.title

      table.table.table-striped.table-bordered
         tr
            td Description
            td = @dish.description
         tr
            td Cost
            td = number_to_currency(@dish.cost, precision: 2)
         tr
            td Pax
            td = @dish.pax
         tr
            td Vegetarian
            td = @dish.vegetarian
         tr
            td Create date
            td = @dish.created_at

      = link_to '+', like_dish_path(@dish), method: :put, class: "btn btn-default btn-sm"
      = @dish.get_upvotes.size
      | - upvotes
      br
      = link_to '-', dislike_dish_path(@dish), method: :put , class: "btn btn-default btn-sm"
      = @dish.get_downvotes.size 
      | - downvotes
      .back_url = link_to 'Back', dishes_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RamsayfanRobin
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container    
       #dishes_devise
         - if fan_signed_in?
            ul
               li = "Welcome #{current_fan.first_name}"
               li = link_to 'Sign out', destroy_fan_session_url, method: :delete
               li = link_to 'Edit Profile', edit_fan_registration_url(current_fan.id)
               li = link_to 'My dishes', dishes_mydishes_dishes_path
               li = link_to 'Home page', dishes_path
         - else
            ul
               li = link_to 'Sign in',  new_fan_session_url
               li = link_to 'Sign up',  new_fan_registration_url

       = yield